# See https://cloud.google.com/cloud-build/docs/build-config

timeout: 1200s
options:
  substitution_option: ALLOW_LOOSE
steps:
  - name: 'gcr.io/k8s-staging-test-infra/gcb-docker-gcloud:v20211118-2f2d816b90'
    entrypoint: make
    env:
    - DOCKER_CLI_EXPERIMENTAL=enabled
    - VERSION=$_GIT_TAG
    - BASE_REF=$_PULL_BASE_REF
    args:
    - release-staging
substitutions:
  _GIT_TAG: '12345'
  _PULL_BASE_REF: 'master'
