apiVersion: apps/v1
kind: Deployment
metadata:
  name: trigger
  labels:
    app: trigger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trigger
  template:
    metadata:
      labels:
        app: trigger
    spec:
      containers:
      - name: trigger
        image: trigger
        livenessProbe:
          httpGet:
            scheme: HTTP
            port: 2113
            path: /healthz
          initialDelaySeconds: 10
          timeoutSeconds: 60
