/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/kubernetes-sigs/kube-storage-version-migrator/pkg/apis/migration/v1alpha1"
	"k8s.io/apimachinery/pkg/api/errors"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/tools/cache"
)

// StorageVersionMigrationLister helps list StorageVersionMigrations.
type StorageVersionMigrationLister interface {
	// List lists all StorageVersionMigrations in the indexer.
	List(selector labels.Selector) (ret []*v1alpha1.StorageVersionMigration, err error)
	// StorageVersionMigrations returns an object that can list and get StorageVersionMigrations.
	StorageVersionMigrations(namespace string) StorageVersionMigrationNamespaceLister
	StorageVersionMigrationListerExpansion
}

// storageVersionMigrationLister implements the StorageVersionMigrationLister interface.
type storageVersionMigrationLister struct {
	indexer cache.Indexer
}

// NewStorageVersionMigrationLister returns a new StorageVersionMigrationLister.
func NewStorageVersionMigrationLister(indexer cache.Indexer) StorageVersionMigrationLister {
	return &storageVersionMigrationLister{indexer: indexer}
}

// List lists all StorageVersionMigrations in the indexer.
func (s *storageVersionMigrationLister) List(selector labels.Selector) (ret []*v1alpha1.StorageVersionMigration, err error) {
	err = cache.ListAll(s.indexer, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.StorageVersionMigration))
	})
	return ret, err
}

// StorageVersionMigrations returns an object that can list and get StorageVersionMigrations.
func (s *storageVersionMigrationLister) StorageVersionMigrations(namespace string) StorageVersionMigrationNamespaceLister {
	return storageVersionMigrationNamespaceLister{indexer: s.indexer, namespace: namespace}
}

// StorageVersionMigrationNamespaceLister helps list and get StorageVersionMigrations.
type StorageVersionMigrationNamespaceLister interface {
	// List lists all StorageVersionMigrations in the indexer for a given namespace.
	List(selector labels.Selector) (ret []*v1alpha1.StorageVersionMigration, err error)
	// Get retrieves the StorageVersionMigration from the indexer for a given namespace and name.
	Get(name string) (*v1alpha1.StorageVersionMigration, error)
	StorageVersionMigrationNamespaceListerExpansion
}

// storageVersionMigrationNamespaceLister implements the StorageVersionMigrationNamespaceLister
// interface.
type storageVersionMigrationNamespaceLister struct {
	indexer   cache.Indexer
	namespace string
}

// List lists all StorageVersionMigrations in the indexer for a given namespace.
func (s storageVersionMigrationNamespaceLister) List(selector labels.Selector) (ret []*v1alpha1.StorageVersionMigration, err error) {
	err = cache.ListAllByNamespace(s.indexer, s.namespace, selector, func(m interface{}) {
		ret = append(ret, m.(*v1alpha1.StorageVersionMigration))
	})
	return ret, err
}

// Get retrieves the StorageVersionMigration from the indexer for a given namespace and name.
func (s storageVersionMigrationNamespaceLister) Get(name string) (*v1alpha1.StorageVersionMigration, error) {
	obj, exists, err := s.indexer.GetByKey(s.namespace + "/" + name)
	if err != nil {
		return nil, err
	}
	if !exists {
		return nil, errors.NewNotFound(v1alpha1.Resource("storageversionmigration"), name)
	}
	return obj.(*v1alpha1.StorageVersionMigration), nil
}
